apiVersion: apps/v1
kind: Deployment
metadata:
  name: british-spoken-time
  labels:
    app: british-spoken-time
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: british-spoken-time
  template:
    metadata:
      labels:
        app: british-spoken-time
        version: v1
    spec:
      containers:
      - name: british-spoken-time
        image: british-spoken-time:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production"
        - name: JAVA_OPTS
          value: "-Xmx512m -Xms256m"
        envFrom:
        - configMapRef:
            name: british-spoken-time-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 10
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
