apiVersion: v1
kind: Service
metadata:
  name: british-spoken-time
  labels:
    app: british-spoken-time
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: british-spoken-time
---
apiVersion: v1
kind: Service
metadata:
  name: british-spoken-time-nodeport
  labels:
    app: british-spoken-time
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: british-spoken-time
